### ISSUE TITLE
Remove .settings files

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-shelter#11]
It seems the .settings folder was added by mistake. Given we try keeping those projects IDE neutral it should be removed unless there is a striking argument against.

**Comment by msgilligan** [comment]
Yes, IDE neutral is the way to go. I'm on IntelliJ and have been adding IntelliJ temp/project files to `.gitignore`. If no one objects, I can do the same for `.settings/` to close out this issue.

**Comment by keilw** [comment]
Sure, please do. The folder should also go, not just .gitignore

**Comment by msgilligan** [comment]
Yes, it has to be deleted and then ignored.

**Comment by msgilligan** [comment]
Deleted: 4cbe3a5b98246b5033a29c869de35ff1ab4375a2
Ignored: 40c8d85184eb07ff82af73e02a16ed8634a005ee
