### ISSUE TITLE
Package name of Groovy module

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-shelter#20]
It would be fair, to use org.javamoney.shelter or something else (like *groovy) for the Groovy modules instead of a personal com domain.

**Comment by msgilligan** [comment]
Yeah, that's a placeholder. I don't think we should use anything in the groovy.* space until we get a little further along. `org.javamoney.shelter` seems like the right choice for now.

**Comment by keilw** [comment]
The module would however need something under *shelter, to identify each bundle.
