### ISSUE TITLE
Java EE essential

### ISSUE THREAD

**Issue by otaviojava** [JavaMoney/javamoney-shelter#21]
The proposal is create a new project, Java EE essential, that has goal to have support to Java EE 7. 
This include: 

*  **JSF:** Conversor to CurrencyUnit, MonetaryAmount, using each implementation and using MonetaryAmountFormat.
* **JPA:** Conversor to persist on database using: just Currency, just Number, both option using toString and parse defult, or each on with a specific column, one to currency and another one to Number.
* **JAX-RS:** Parser to read and write to Currency and MonetaryAmount
* **CDI:** producer to monetaryAmount, qualifier to all implementation and default
* **JSON:** Parser and Binding 
* **Bean Validation:** Special Validators or Min/Max constraints for monetary amounts, etc.

**Comment by keilw** [comment]
Please ensure, the POMs follow the parent:
<dependency>
  <groupId>org.javamoney.shelter</groupId>
  <artifactId>javamoney-${module}<artifactId>
  <versionId>the current version</version>
</dependency>

${module} could be anything like "jsf", "jpa", etc. as long as they don't overlap other modules in **shelter**.

**Comment by keilw** [comment]
There are other likely candidates for EE features:
* JSON: Parser and Binding if the JSR for it gets ready, in the meantime Jackson or others could do, see https://github.com/unitsofmeasurement/jackson-module-unitsofmeasure
* Bean Validation: Special Validators or Min/Max constraints for monetary amounts, etc.

**Comment by keilw** [comment]
Replaced by javamoney-midas
