### ISSUE TITLE
moduleVersion of Groovy module

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-shelter#24]
The Groovy module currently defines
moduleVersion=0.1-dev

Is "-dev" an established standard for Groovy and its module system, or would "-SNAPSHOT" also work?
It is fair to number the sub-module 0.1 as it is behind the other Shelter modules, most of which handled under 0.6-SNAPSHOT now, but at some point it would be great to align this module version with the rest of Shelter.

**Comment by stokito** [comment]
Groovy hasn't any standard for "-dev" and it follows usual Maven rules.

**Comment by keilw** [comment]
Then I'd use -SNAPSHOT regardless of the version before it (0.1 seems fine as of now)

**Comment by stokito** [comment]
:+1: go ahead
