### ISSUE TITLE
Rename "Digital" to "Crypto"

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-shelter#32]
The term "Digital" in `digital-currency` should be changed to "Crypto" as the module contains mainly **Cryptocurrencies** like Bitcoin. 

Should there be support for other "Virtual Currencies" or "Digital Currencies" a new module could be revived under that name.

**Comment by msgilligan** [comment]
Maybe we should just remove that module. I've created something similar in a module of the [ConsensusJ](https://github.com/ConsensusJ/consensusj) project that I'm testing, improving, and using in other projects. I've also created support for OmniLayer currencies and have some (not-yet-published) Ethereum support, too.

**Comment by msgilligan** [comment]
Yes, of course!

**Comment by keilw** [comment]
The parent project should still be there, but if something "graduated" from the incubator or a more mature equivalent is available, see Physikal for JSR 363 we can always deprecate something from the Shelter. It is not as easy to archive the entire shelter, guess versioning and releasing some parts might work best here.
