### ISSUE TITLE
Add Groovy support

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-shelter#6]
Umbrella Task for Groovy support, which should include:

* Support for arithmetic with operators using Groovy MetaClass extensions
* Support currency code properties on `Number` interface, e.g. `def amount = 1.eur`

**Comment by msgilligan** [comment]
Working on it... ;)

**Comment by keilw** [comment]
No it's mainly an umbrella task;-)

**Comment by msgilligan** [comment]
I can edit your comments! Hope you don't mind. I started a bullet list on the first comment where we can add a list of features that we want to see for proper Groovy support.

**Comment by msgilligan** [comment]
I'm proposing we submit this work to the Groovy project as a Groovy module. See Issue #9.
