### ISSUE TITLE
Use Spock tests for digital-currency/bitcoin module

### ISSUE THREAD

**Issue by msgilligan** [JavaMoney/javamoney-shelter#8]
As you may have noticed, I'm a big fan of the [Spock Framework](https://spock-framework.readthedocs.org/). Would anyone else be interested in using it instead of (or in addition to) JUnit for the 'digital-currency/bitcoin' module?

**Comment by stokito** [comment]
:+1:  I even cant image how to write useful tests without Spock

**Comment by msgilligan** [comment]
@keilw What do you think?

I would initially add Spock support to the POM and convert the JUnit file that I wrote to Spock. JUnit and Spock could co-exist for a while, but we could also decide to go 100% Spock.

**Comment by keilw** [comment]
All tests I know for main JSR 354 were changed from JUnit to TestNG AFAIK, but being an expert in Agile, DevOps or BDD myself I see no problem using Spock at least in the Shelter. Could provide experience for other JavaMoney projects later;-) so 
+1

**Comment by msgilligan** [comment]
OK, I'll try to put together a pull request for it within the next week. I'll update `pom.xml` and create a few sample Spock tests (converting what I've already written.)

**Comment by msgilligan** [comment]
Implemented in PR #14.
